### ISSUE TITLE
Request for a standalone version of the Anki Addon

### ISSUE THREAD

**Issue by CodeWithMa** [Aquafina-water-bottle/local-audio-yomichan#7]
Hello,

I really appreciate the functionality of the Anki addon that you have created. However, I was wondering if it would be possible to have a standalone version of the application. This would allow me to use the application without having to always keep Anki open.

I understand that the addon was designed specifically for Anki and may have dependencies that require it to be integrated with the Anki platform.

Would it be possible to consider creating a standalone version of the application? I believe this would be a great addition to your project and would provide more options for users.

Thank you for your consideration.

**Comment by Aquafina-water-bottle** [comment]
Hey,

Thanks for the suggestion! There was actually a minor internal issue that originally prevented me from implementing this, but I believe it should be fixed now. Before today, the following `__init__.py` file was always importing anki modules, but this `if` statement should hopefully solve it so it only gets imported if it was ran by Anki:

https://github.com/Aquafina-water-bottle/local-audio-yomichan/blob/2ba3bc7c4d102062f2cbba2607dff611143bcf42/plugin/__init__.py#L5-L10

With all that being said, you should be able to run the server without Anki now. I added some instructions on how to run it [here](https://github.com/Aquafina-water-bottle/local-audio-yomichan#running-without-anki). Please let me know if it works!

**Comment by CodeWithMa** [comment]
> With all that being said, you should be able to run the server without Anki now. I added some instructions on how to run it [here](https://github.com/Aquafina-water-bottle/local-audio-yomichan#running-without-anki). Please let me know if it works!

Wow, you're lightning fast! I did what you said and it is working like a charm. Thanks a ton for your help, it's seriously appreciated!
